Vagrant.configure("2") do |config|
  # Налаштування VirtualBox як провайдера
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 2
    vb.gui = true
  end

  # Налаштування SSH для доступу до віртуальних машин
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"

  # Віртуальна машина для Windows
  config.vm.define "windows" do |windows|
    windows.vm.box = "hashicorp/bionic64"  # Замість реальної Windows можна використовувати Linux образ
    windows.vm.provision "shell", inline: <<-SHELL
      dotnet nuget add source http://192.168.56.1:5000/v3/index.json --name BaGet --store-password-in-clear-text

      dotnet tool install --global ILugovoy --version 1.0.0 --add-source http://192.168.56.1:5000/v3/index.json
    SHELL

  end

  # Віртуальна машина для Linux
  config.vm.define "linux" do |linux|
    linux.vm.box = "ubuntu/focal64"  
    linux.vm.provision "shell", inline: <<-SHELL
      wget https://dot.net/v1/dotnet-install.sh
      chmod +x dotnet-install.sh
      ./dotnet-install.sh --install-dir /usr/share/dotnet
      export PATH=$PATH:/usr/share/dotnet
      dotnet nuget add source http://192.168.56.1:5000/v3/index.json --name BaGet --store-password-in-clear-text

      dotnet tool install --global ILugovoy --version 1.0.0 --add-source http://192.168.56.1:5000/v3/index.json
    SHELL
   end
  # Віртуальна машина для macOS (насправді тут використовується Ubuntu, оскільки macOS не підтримується у Vagrant)
  config.vm.define "mac" do |mac|
    mac.vm.box = "ubuntu/focal64"
    mac.vm.provision "shell", inline: <<-SHELL
      wget https://dot.net/v1/dotnet-install.sh
      chmod +x dotnet-install.sh
      ./dotnet-install.sh --install-dir /usr/share/dotnet
      export PATH=$PATH:/usr/share/dotnet
      dotnet nuget add source http://192.168.56.1:5000/v3/index.json --name BaGet --store-password-in-clear-text

      dotnet tool install --global ILugovoy --version 1.0.0 --add-source http://192.168.56.1:5000/v3/index.json
    SHELL
  end
end
